theme = "seoul256-dark-hard"

[editor]
true-color = true
bufferline = "always"
rulers = [120]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal]
C-k = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-r = [":reload-all"]
